### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by nyov** [kallaballa/WesnothReplayToXML#1]
I like this, because I have no patience for this 'WML' stuff which only exists because... ego. ("I didn't like the XML hype so I rolled my own"...). Nevermind.  

Can this actually do back-to-back conversions which remain syntactically correct?

Please expand your README to include the required libraries for compilation? Just "make" doesn't _quite_ cut it. Thanks.
```
...
g++ -L/opt/local/lib -s  -o wml2xml serialization/parser.o tstring.o serialization/tokenizer.o config_attribute_value.o config.o serialization/preprocessor.o game_config.o color.o color_range.o log.o filesystem_boost.o filesystem_common.o serialization/unicode.o serialization/string_utils.o gettext_boost.o serialization/binary_or_text.o version.o font/constants.o -lm -lboost_iostreams `pkg-config --libs sdl` -lboost_filesystem -lboost_system -lboost_locale
/usr/bin/ld: cannot find -lboost_iostreams
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_locale
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:22: wml2xml] Error 1
make[1]: Leaving directory '/tmp/xxx/WML2XML/src'
make: *** [Makefile:77: dirs] Error 2
```
(I mean, they're rather obvious, but still.)
/edit: for debian, that's
```
apt-get install libboost-system-dev libboost-locale-dev libboost-iostreams-dev libboost-filesystem-dev
```

**Comment by kallaballa** [comment]
> Can this actually do back-to-back conversions which remain syntactically correct?

I don't know :)

> Please expand your README to include the required libraries for compilation? Just "make" doesn't quite cut it. Thanks.

Done

**Comment by nyov** [comment]
Thanks. And it works as far as I tested it :)
